# Goal
geometry_msgs/Point goal_orientation
# string measure # rad/deg working with rad for now (Maybe add some check for radians/degrees)
int32 timeout_sec
float32 epsilon
---
# Result
bool distancer_on_powerlines
---
# Feedback
string motors_status # if both closed (separator is on line)

