#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.05

# PID gains --> Increase gains even more, test it in simulation, CHECK REAL ROBOT SAFETY
x_proportional_gain: 200
y_proportional_gain: 200
z_proportional_gain: 2000
x_integral_gain: 0.0
y_integral_gain: 0.0
z_integral_gain: 0.0
x_derivative_gain: 0.0
y_derivative_gain: 0.0
z_derivative_gain: 0.0

angular_proportional_gain: 0.5
angular_integral_gain: 0.0
angular_derivative_gain: 0.0